const char *ezWxLua = 
"package.cpath = package.cpath..\";./?.dll;./?.so;../lib/?.so;../lib/vc_dll/?.dll;../lib/bcc_dll/?.dll;../lib/mingw_dll/?.dll;\"\n"
"require(\"wx\")\n"

"wxID_USER_Index = 1000\n"

"-------------------------------------------------------------------------------\n"
"-- Resource\n"
"-------------------------------------------------------------------------------\n"

"function os.isfile(name)\n"
"   local f=io.open(name,\"r\")\n"
"   if f~=nil then io.close(f) return true else return false end\n"
"end\n"

"function dump_table(data)\n"
"	for k,v in pairs(data) do\n"
"		print( k, v )\n"
"	end\n"
"end\n"

"function GetMenuBitmap(name,size)\n"
" if name == \"exit\" then\n"
"  return wx.wxArtProvider.GetBitmap(wx.wxART_QUIT, wx.wxART_MENU, wx.wxSize(size, size))\n"
" end\n"
" if name == \"help\" then\n"
"  return wx.wxArtProvider.GetBitmap(wx.wxART_HELP, wx.wxART_MENU, wx.wxSize(size, size))\n"
" end\n"
"end\n"

"function GetToolBitmap(name,size)\n"
" if name == \"exit\" then\n"
"  return wx.wxArtProvider.GetBitmap(wx.wxART_QUIT, wx.wxART_TOOLBAR, wx.wxSize(size, size))\n"
" end\n"
" if name == \"help\" then\n"
"  return wx.wxArtProvider.GetBitmap(wx.wxART_HELP, wx.wxART_TOOLBAR, wx.wxSize(size, size))\n"
" end\n"
"end\n"

"function GetBitmap(xpm_table)\n"
"     return wx.wxBitmap(xpm_table)\n"
"end\n"
"	\n"
"function GetBitmapFile( filename )\n"
"	if os.isfile( filename ) then\n"
"		return wx.wxBitmap( filename, wx.wxBITMAP_TYPE_ANY )\n"
"	else\n"
"		return nil\n"
"	end\n"
"end\n"

"function GetIcon(name)\n"
"     local icon = wx.wxIcon()\n"
"	 if type(name) == \"string\" then\n"
"		icon:CopyFromBitmap(wx.wxBitmap(name))\n"
"	 end\n"
"     return icon\n"
"end\n"

"-------------------------------------------------------------------------------\n"
"-- Dialogs\n"
"-------------------------------------------------------------------------------\n"

"function Message(parent,caption,message)\n"
"    return wx.wxMessageBox( message, caption, wx.wxOK + wx.wxCENTRE, parent, -1, -1 )\n"
"end\n"

"function OpenFileDialog(parent,defaultDir,multiple,save)\n"
"    local style = 0\n"
" if save == nil or save == False then\n"
"  style = wx.wxFD_OPEN + wx.wxFD_FILE_MUST_EXIST \n"
" else \n"
"  style = wx.xFD_SAVE + wx.wxFD_OVERWRITE_PROMPT\n"
" end\n"
" if multiple ~= nil and multiple == true then\n"
"  style = style + wx.wxFD_MULTIPLE \n"
" end\n"
"    if defaultDir == nil then \n"
"  defaultDir = \"\" \n"
" end\n"
"    local dlg = wx.wxFileDialog(parent,\"Choose a file\",defaultDir,\"\",\"*.*\",style)\n"
"    local rv = dlg:ShowModal()\n"
"    if rv == wx.wxID_OK then\n"
"  --[[\n"
"        if multiple == true then\n"
"            files = []\n"
"            for file in dlg.GetFilenames():\n"
"                files.append( os.path.join(dlg.GetDirectory(), file) )\n"
"            return files\n"
"        else:]]\n"
"        return dlg:GetDirectory() .. \"\\\\\" .. dlg:GetFilename()\n"
" end\n"
"    return nil \n"
"end\n"

"-------------------------------------------------------------------------------\n"
"-- Menu\n"
"-------------------------------------------------------------------------------\n"

"function Menu(parent,menu_table)\n"
"    local menu = wx.wxMenu()\n"
"    for i, m in ipairs(menu_table) do\n"
"        local item\n"
"        if type(m.Name) == \"string\" then \n"
"            if type(m.Value) == \"table\" then\n"
"                submenu = Menu( parent, m.Value )\n"
"                menu:Append( submenu, m.Name ) \n"
"            end  \n"
"            if type(m.Value) == \"function\" then\n"
"                item = wx.wxMenuItem( menu, wxID_USER_Index, m.Name, \"\", wx.wxITEM_NORMAL )\n"
"    if m.Icon ~= nil then\n"
"     item:SetBitmap(GetMenuBitmap(m.Icon,16))\n"
"    end\n"
"                menu:Append( item )\n"
"                parent:Connect(wxID_USER_Index, wx.wxEVT_COMMAND_MENU_SELECTED, m.Value)\n"
"                wxID_USER_Index = wxID_USER_Index + 1\n"
"            end\n"
"        end  \n"
"    end    \n"
"    return menu\n"
"end\n"

"function MenuBar(parent,menubar_table)\n"
"    local menubar = wx.wxMenuBar( 0 )\n"
"    for i, m in ipairs(menubar_table) do\n"
"        local menu\n"
"        if type(m.Name) == \"string\" then \n"
"            local item\n"
"            if type(m.Value) == \"table\" then\n"
"                menu = Menu( parent, m.Value )\n"
"                menubar:Append( menu, m.Name ) \n"
"            end\n"
"            if type(m.Value) == \"function\" then\n"
"                item = wx.wxMenuItem( menubar, wxID_USER_Index, m.Name, \"\", wx.wxITEM_NORMAL )\n"
"                menubar:Append( item )\n"
"                parent:Connect(wxID_USER_Index, wx.wxEVT_COMMAND_MENU_SELECTED, m.Value)\n"
"                wxID_USER_Index = wxID_USER_Index + 1\n"
"            end\n"
"        end   \n"
"    end\n"
"    return menubar\n"
"end\n"

"-------------------------------------------------------------------------------\n"
"-- ToolBar\n"
"-------------------------------------------------------------------------------\n"
"--[[\n"
"    control:AddTool(wx.wxID_ANY, \"A tool 1\", bmp, \"Help for a tool 1\", wx.wxITEM_NORMAL)\n"
"    control:AddTool(wx.wxID_ANY, \"A tool 2\", bmp, \"Help for a tool 2\", wx.wxITEM_NORMAL)\n"
"    control:AddSeparator()\n"
"    control:AddCheckTool(wx.wxID_ANY, \"A check tool 1\", bmp, wx.wxNullBitmap, \"Short help for checktool 1\", \"Long help for checktool \")\n"
"    control:AddCheckTool(wx.wxID_ANY, \"A check tool 2\", bmp, wx.wxNullBitmap, \"Short help for checktool 2\", \"Long help for checktool 2\")\n"
"    AddControl(\"wxToolBar\", control)\n"
"]]\n"
"function CreateToolBar(parent,toolbar_table)\n"
" local flags = wx.wxTB_FLAT + wx.wxTB_HORIZONTAL + wx.wxTB_TEXT\n"
" local toolbar = parent:CreateToolBar( flags, wx.wxID_ANY )\n"
"    for i, m in ipairs(toolbar_table) do\n"
"  local tool\n"
"  local icon\n"
"  local tooltip\n"
"  local name = m.Name\n"
"  if m.Name ~= nil and m.Name == '-' then\n"
"   toolbar:AddSeparator()\n"
"  else\n"
"   if m.Icon == nil then icon = wx.NullBitmap else icon = GetToolBitmap(m.Icon,32) end\n"
"   if m_ToolTip == nil then tooltip = \"\" else tooltip = m.ToolTip end\n"
"   if m.Name == nil then\n"
"    flags = flags + wx.wxTB_TEXT\n"
"    name = \"\"\n"
"   end\n"
"   tool = toolbar:AddTool(wxID_USER_Index, name, icon, tooltip, wx.wxITEM_NORMAL)\n"
"  \n"
"   if m.ToolTip ~= nil then toolbar:SetToolShortHelp( wxID_USER_Index, m.ToolTip) end\n"
"   if m.Value == nil then tool:Enable( false ) else \n"
"    toolbar:Connect( wxID_USER_Index, wx.wxEVT_COMMAND_TOOL_CLICKED, m.Value )\n"
"   end\n"
"   wxID_USER_Index = wxID_USER_Index + 1\n"
"  end\n"
"    end\n"
"    toolbar:Realize()\n"
" \n"
"--[[\n"
"    local toolbar = wx.wxToolBar(parent, ID_TOOLBAR, wx.wxDefaultPosition, wx.wxDefaultSize)\n"
"    for i, m in ipairs(toolbar_table) do\n"
"  local tool = toolbar:AddTool(wx.wxID_ANY, m.Name, m.Icon, m.ToolTip, wx.wxITEM_NORMAL)\n"
"    end\n"
"    return toolbar\n"
" ]]\n"
"end\n"

"-------------------------------------------------------------------------------\n"
"-- StatusBar\n"
"-------------------------------------------------------------------------------\n"

"function StatusBar(parent,count)\n"
"    return parent:CreateStatusBar( count, 0, wxID_STATUS )\n"
"end\n"

"-------------------------------------------------------------------------------\n"
"-- Misc\n"
"-------------------------------------------------------------------------------\n"

"function SetToolTip(ctrl)\n"
"end\n"

"-------------------------------------------------------------------------------\n"
"-- Controls\n"
"-------------------------------------------------------------------------------\n"

"function InitCtrl(ctrl,handler)\n"
"	if ctrl.proportion == nil then ctrl.proportion = 0 end\n"
"	if ctrl.expand == nil then ctrl.expand = true end\n"
"	if ctrl.border == nil then ctrl.border = 1 end\n"
"	ctrl.SetLayoutParam = function( proportion, expand, border )\n"
"		ctrl.proportion = proportion\n"
"		ctrl.expand = expand\n"
"		ctrl.border = border\n"
"	end \n"
"end\n"

"function InitItemContainer(newCtrl)\n"
"	newCtrl.Clear  = function() return newCtrl.ctrl:Clear() end\n"
"	newCtrl.Append = function(value) return newCtrl.ctrl:Append(value) end\n"
"	newCtrl.Insert = function(value,index) return newCtrl.ctrl:Insert(value,index) end\n"
"	newCtrl.Delete = function(index) return newCtrl.ctrl:Delete(index) end\n"
"	newCtrl.Select = function(index) return newCtrl.ctrl:Select(index) end\n"
"	newCtrl.GetCount  = function() return newCtrl.ctrl:GetCount() end\n"
"	newCtrl.GetSelection  = function() return newCtrl.ctrl:GetSelection() end\n"
"	newCtrl.GetString = function(index) return newCtrl.ctrl:GetString(index) end\n"
"end\n"

"function StaticText(parent,ctrl)\n"
"	local label = {}\n"
"	label.ctrl = wx.wxStaticText( parent, wx.wxID_ANY, ctrl.data,\n"
"					wx.wxDefaultPosition, wx.wxDefaultSize) --wx.wxSize(-1,50)\n"
"	ctrl.proportion = 0\n"
"	ctrl.expand = false\n"
"	ctrl.border = 1\n"
"	return label\n"
"end\n"

"function StaticBitmap(parent,ctrl) --TODO: Te be tested\n"
"	local label = {}\n"
"	local flag = wx.wxALIGN_CENTER\n"
"	local bitmap = wx.Bitmap( ctrl.data, wx.BITMAP_TYPE_ANY )\n"
"	label.ctrl = wx.wxStaticText( parent, wx.wxID_ANY, bitmap,\n"
"					wx.wxDefaultPosition, wx.wxDefaultSize, flag) --wx.wxSize(-1,50)\n"
"	label.ctrl.Bind( wx.EVT_SIZE, function(ctrl,event) \n"
"			event:Skip()\n"
"		end )\n"
"	label.proportion = 0\n"
"	label.expand = false\n"
"	label.border = 1\n"
"	return label\n"
"end\n"

"function Button(parent,ctrl)\n"
"	local button = {}\n"
"	button.ctrl = wx.wxButton( parent, wxID_USER_Index, ctrl.data,\n"
"					wx.wxDefaultPosition, wx.wxDefaultSize)\n"
"	button.id = wxID_USER_Index\n"
"	wxID_USER_Index = wxID_USER_Index + 1\n"
"	InitCtrl(button)    \n"
"	if ctrl.handler ~= nil then\n"
"		parent:Connect(button.id, wx.wxEVT_COMMAND_BUTTON_CLICKED, ctrl.handler )\n"
"	end      \n"
"	return button\n"
"end\n"

"function BitmapButton(parent,ctrl) --TODO: To be tested\n"
"	local button = {}\n"
"	button.ctrl = wx.wxBitmapButton( parent, wxID_USER_Index, ctrl.data,\n"
"					wx.wxDefaultPosition, wx.wxDefaultSize)\n"
"	wxID_USER_Index = wxID_USER_Index + 1\n"
"	InitCtrl(button) \n"
"	return button \n"
"end\n"

"function TextCtrl(parent,ctrl)\n"
"	local text = {}\n"
"	text.ctrl = wx.wxTextCtrl(parent, wxID_USER_Index, ctrl.data,\n"
"					wx.wxDefaultPosition, wx.wxDefaultSize,\n"
"					wx.wxTE_PROCESS_ENTER ) \n"
"	text.id = wxID_USER_Index\n"
"	wxID_USER_Index = wxID_USER_Index + 1\n"
"	InitCtrl(text) \n"
" \n"
"	local dropTarget = wx.wxLuaFileDropTarget();\n"
"	dropTarget.OnDropFiles = function(self, x, y, filenames)\n"
"		text.ctrl:Clear()\n"
"		for i = 1, #filenames do\n"
"			if i >= 2 then text.ctrl:AppendText(';') end\n"
"			text.ctrl:AppendText(filenames[i])    \n"
"		end\n"
"		return true\n"
"	end\n"
"	text.ctrl:SetDropTarget(dropTarget)\n"
"	text.Clear = function() text.ctrl:Clear() end\n"
"	text.AppendText = function(data) text.ctrl:AppendText(data) end \n"
"	return text \n"
"end\n"

"function MLTextCtrl(parent,ctrl)\n"
"	local text = {}\n"
"    text.ctrl = wx.wxTextCtrl(parent, wxID_USER_Index, ctrl.data,\n"
"				wx.wxDefaultPosition, wx.wxDefaultSize,\n"
"				wx.wxTE_MULTILINE+wx.wxTE_DONTWRAP) \n"
"    text.id = wxID_USER_Index\n"
"	wxID_USER_Index = wxID_USER_Index + 1\n"
"	InitCtrl(text)  \n"
"    return text\n"
"end\n"

"function StyledText(parent,ctrl)\n"
"	local stc = {}\n"
"	local style = 0\n"
"	local name = \"wxStyledTextCtrl\"\n"
"    stc.ctrl = wxstc.wxStyledTextCtrl(parent, wxID_USER_Index, \n"
"				wx.wxDefaultPosition, wx.wxDefaultSize, style, name ) \n"
"    stc.id = wxID_USER_Index\n"
"	wxID_USER_Index = wxID_USER_Index + 1 \n"
"	\n"
"	stc.enableLineNumber = function()\n"
"        stc.ctrl:SetMargins(0, 0)\n"
"        stc.ctrl:SetMarginType(1, wxstc.wxSTC_MARGIN_NUMBER)\n"
"        stc.ctrl:SetMarginMask(2, wxstc.wxSTC_MASK_FOLDERS)\n"
"        stc.ctrl:SetMarginSensitive(2, True)\n"
"        stc.ctrl:SetMarginWidth(1, 32) -- 2,25\n"
"        stc.ctrl:SetMarginWidth(2, 16) -- 2,25	\n"
"	end\n"
"	\n"
"	stc.enableLineNumber();\n"
"	\n"
"	return stc\n"
"end\n"

"function Choice(parent,ctrl)\n"
"	local newCtrl = { }\n"
"	local items = { }\n"
"	local value = nil\n"
"	if ctrl.items ~= nil then items = ctrl.items end\n"
"	if ctrl.value ~= nil then value = ctrl.value end\n"
"	newCtrl.ctrl = wx.wxChoice( parent, wxID_USER_Index, \n"
"					wx.wxDefaultPosition, wx.wxDefaultSize, \n"
"					items, 0, wx.wxDefaultValidator)\n"
"    newCtrl.id = wxID_USER_Index\n"
"    wxID_USER_Index = wxID_USER_Index + 1\n"
"    if value ~= nil then newCtrl.ctrl:SetSelection(value) end\n"
"	if ctrl.handler ~= nil then\n"
"		parent:Connect(newCtrl.id, wx.wxEVT_COMMAND_CHOICE_SELECTED, ctrl.handler )\n"
"	end      \n"
"    InitCtrl(newCtrl) 	\n"
"	InitItemContainer(newCtrl)\n"
"	newCtrl.GetValue = function() return newCtrl.ctrl:GetCurrentSelection() end\n"
"	newCtrl.GetText  = function() return newCtrl.ctrl:GetString(newCtrl.ctrl:GetCurrentSelection()) end\n"
"	return newCtrl\n"
"end\n"

"function ComboBox(parent,ctrl)\n"
"	local newCtrl = { }\n"
"	local items = { }\n"
"	local value = \"\"\n"
"	if ctrl.items ~= nil then items = ctrl.items end\n"
"	if ctrl.value ~= nil then value = ctrl.value end\n"
"	newCtrl.ctrl = wx.wxComboBox( parent, wxID_USER_Index, value,\n"
"					wx.wxDefaultPosition, wx.wxDefaultSize, \n"
"					items, 0, wx.wxDefaultValidator)\n"
"    newCtrl.id = wxID_USER_Index\n"
"    wxID_USER_Index = wxID_USER_Index + 1\n"
"	if ctrl.handler ~= nil then\n"
"		parent:Connect(newCtrl.id, wx.wxEVT_COMMAND_COMBOBOX_SELECTED, ctrl.handler )\n"
"	end      \n"
"    InitCtrl(newCtrl) 	\n"
"	InitItemContainer(newCtrl)\n"
"	newCtrl.GetValue = function() return newCtrl.ctrl:GetValue() end\n"
"	newCtrl.GetText  = function() return newCtrl.ctrl:GetValue() end\n"
"	return newCtrl\n"
"end\n"


"function ListBox(parent,ctrl)\n"
"	local newCtrl = { }\n"
"	local items = { }\n"
"	local value = \"\"\n"
"	if ctrl.items ~= nil then items = ctrl.items end\n"
"	if ctrl.value ~= nil then value = ctrl.value end\n"
"	newCtrl.ctrl = wx.wxListBox( parent, wxID_USER_Index, \n"
"					wx.wxDefaultPosition, wx.wxDefaultSize, \n"
"					items, 0, wx.wxDefaultValidator)\n"
"    newCtrl.id = wxID_USER_Index\n"
"    wxID_USER_Index = wxID_USER_Index + 1\n"
"	if ctrl.handler ~= nil then\n"
"		parent:Connect(newCtrl.id, wx.wxEVT_COMMAND_LISTBOX_SELECTED, ctrl.handler )\n"
"	end      \n"
"    InitCtrl(newCtrl) 	\n"
"	InitItemContainer(newCtrl)\n"
"	newCtrl.GetValue = function() return newCtrl.ctrl:GetValue() end\n"
"	newCtrl.IsSelected = function(index) return newCtrl.ctrl:IsSelected(index) end\n"
"	return newCtrl\n"
"end\n"

"function ListCtrl(parent)\n"
"    local list = { }\n"
"    list.ctrl = wx.wxListCtrl(parent, wxID_USER_Index,\n"
"                  wx.wxDefaultPosition, wx.wxDefaultSize,\n"
"                  wx.wxLC_REPORT +wx.wxBORDER_SUNKEN)\n"
"    list.id = wxID_USER_Index\n"
"    wxID_USER_Index = wxID_USER_Index + 1\n"
"    InitCtrl(list)\n"
"  \n"
" local dropTarget = wx.wxLuaFileDropTarget();\n"
" dropTarget.OnDropFiles = function(self, x, y, filenames)\n"
"   for i = 1, #filenames do\n"
"    list.ctrl:InsertItem(list.ctrl:GetItemCount()+1, filenames[i])    \n"
"   end\n"
"   return true\n"
"  end\n"
" list.ctrl:SetDropTarget(dropTarget)\n"
" \n"
"    --list:SetImageList(listImageList, wx.wxIMAGE_LIST_SMALL)\n"
"    list.col = 0\n"
"    list.row = 0\n"
"    \n"
" list.Clear = function() list.ctrl:ClearAll() end\n"
" list.Set = function( row, col, label )\n"
"  list.ctrl:SetItem( row, col, label)\n"
" end\n"
"    list.AddColumn = function( label, size )\n"
"        list.ctrl:InsertColumn(list.col, label)\n"
"        list.ctrl:SetColumnWidth(list.col, size)\n"
"        list.col = list.col + 1\n"
"    end\n"
"    list.AddColumns = function( labels, widths )\n"
"        if labels == nil then return end\n"
"        for col = 1, #labels do\n"
"            list.ctrl:InsertColumn( col-1, labels[col])\n"
"            list.col = list.col + 1\n"
"        end\n"
"        if widths == nil then return end\n"
"        for col = 1, #widths do\n"
"            list.ctrl:SetColumnWidth(col-1, widths[col])\n"
"        end\n"
"    end    \n"
"    list.AddRow = function( row )\n"
"        list.ctrl:InsertItem( list.row, row[1] )\n"
"        for col = 2, #row do\n"
"            list.ctrl:SetItem( list.row, col-1, row[col])\n"
"        end\n"
"        list.row = list.row + 1\n"
"    end\n"
"    \n"
"    --if cols ~= nil then list.AddColumns( cols, colwidths ) end\n"
" return list\n"
"end\n"


"-------------------------------------------------------------------------------\n"
"-- Container\n"
"-------------------------------------------------------------------------------\n"

"function Panel(parent,content)\n"
"    local panel = { }\n"
"    panel.ctrl = wx.wxPanel( parent, wx.wxID_ANY, wx.wxDefaultPosition, wx.wxDefaultSize, wx.wxTAB_TRAVERSAL )\n"
"    panel.ctrl:SetSizer( Layout( panel.ctrl,content).ctrl )\n"
"    panel.ctrl:Layout()\n"
"    return panel\n"
"end\n"

"function BoxPanel(parent,content)\n"
"    local vbox = VBox()\n"
"    local panel = Panel(parent,content)\n"
"    panel.expand = true\n"
"    panel.proportion = 1\n"
"    vbox.Add(panel)\n"
"    vbox.expand = true\n"
"    vbox.proportion = 1\n"
"    return vbox\n"
"end\n"

"function SplitterWindow(parent,content,direction)\n"
"	local swin = { }\n"
"    swin.ctrl = wx.wxSplitterWindow( parent, wx.wxID_ANY, wx.wxDefaultPosition, wx.wxDefaultSize, 0 --[[wx.wxSP_3D]] )\n"
"    local left_panel = Panel( swin.ctrl, content.children[1] )\n"
"    local right_panel = Panel( swin.ctrl, content.children[2] )\n"
"    if direction == 'horizontal' then\n"
"		swin.ctrl:SplitHorizontally( left_panel.ctrl, right_panel.ctrl, 0 )\n"
"	else\n"
"		swin.ctrl:SplitVertically( left_panel.ctrl, right_panel.ctrl, 0 )\n"
"	end\n"
"    return swin\n"
"end\n"

"function VerticalWindow(parent,content)\n"
"	return SplitterWindow(parent,content,'vertical')\n"
"end\n"

"function HorizontalWindow(parent,content)\n"
"	return SplitterWindow(parent,content,'horizontal')\n"
"end\n"

"function Notebook(parent,content)\n"
"	local note = { }\n"
"    note.ctrl = wx.wxNotebook( parent, wx.wxID_ANY, wx.wxDefaultPosition, wx.wxDefaultSize, 0 )\n"
"    if content ~= nil and content.children ~= nil then\n"
"		for i = 1, #content.children do\n"
"			local panel = Panel( note.ctrl, content.children[i] )\n"
"			local title = tostring(i)\n"
"			if content.title ~= nil and content.title[i] ~= nil then\n"
"				title = content.title[i]\n"
"			end\n"
"			note.ctrl:AddPage( panel.ctrl, title, False ) \n"
"		end\n"
"    end\n"
"    return note\n"
"end\n"

"-------------------------------------------------------------------------------\n"
"-- Sizer\n"
"-------------------------------------------------------------------------------\n"

"function BoxSizer(orient)\n"
"    local sizer = { }\n"
"    if orient == nil then orient = wx.wxVERTICAL end\n"
"	sizer.ctrl = wx.wxBoxSizer( orient )\n"
"	sizer.Add = function(child) \n"
"		local proportion = 0\n"
"		local border = 0\n"
"		local align = wx.wxALIGN_CENTER\n"
"		local flags = align + wx.wxALL\n"
"		if child.expand ~= nil and child.expand == true then flags = flags + wx.wxEXPAND end\n"
"		if child.border ~= nil then border = child.border end \n"
"		if child.proportion ~= nil then proportion = child.proportion end\n"
"		sizer.ctrl:Add( child.ctrl, proportion, flags, border )\n"
"	end\n"
"	sizer.AddSpacer = function(size) \n"
"		if size == nil then size = 0 end\n"
"		sizer.ctrl:Add( 0, 0, 1, wx.wxEXPAND, 5 )\n"
"    end\n"
"    return sizer\n"
"end\n"

"function VBox()\n"
"    return BoxSizer(wx.wxVERTICAL)\n"
"end\n"
"      \n"
"function HBox()\n"
"    return BoxSizer(wx.wxHORIZONTAL)\n"
"end\n"

"function HStaticBox(parent,name) \n"
"    local hsbox = { }\n"
"    local box = wx.wxStaticBox( parent, wx.wxID_ANY, name)\n"
"    hsbox.ctrl = wx.wxStaticBoxSizer( box, wx.wxHORIZONTAL )\n"
"    hsbox.Add = function(child) \n"
"        hsbox.ctrl:Add( child.ctrl, 1, wx.wxEXPAND + wx.wxALL + wx.wxGROW, 1 )\n"
"    end    \n"
"    return hsbox\n"
"end\n"

"-------------------------------------------------------------------------------\n"
"-- Layout\n"
"-------------------------------------------------------------------------------\n"

"function Layout(parent,content) \n"
"    local vbox = VBox()\n"
"    for i, v in ipairs(content) do\n"
"        local hbox = HBox()\n"
"        if type(v) == \"table\" then\n"
"            for j, h in pairs(v) do\n"
"                if type(h) == \"table\" then\n"
"                    local ctrl;\n"
"                    if h.name == \"StaticText\" then\n"
"                        ctrl = StaticText(parent,h)\n"
"                    elseif h.name == \"Button\" then\n"
"                        ctrl = Button(parent,h)\n"
"                    elseif h.name == \"TextCtrl\" then\n"
"                        ctrl = TextCtrl(parent,h)\n"
"                    elseif h.name == \"StyledText\" then\n"
"                        ctrl = StyledText(parent,h)\n"
"                    elseif h.name == \"Choice\" then\n"
"                        ctrl = Choice(parent,h)\n"
"                    elseif h.name == \"ComboBox\" then\n"
"                        ctrl = ComboBox(parent,h)\n"
"                    elseif h.name == \"ListBox\" then\n"
"                        ctrl = ListBox(parent,h)\n"
"                    elseif h.name == \"ListCtrl\" then\n"
"                        ctrl = ListCtrl(parent)\n"
"                    elseif h.name == \"Panel\" then\n"
"                        ctrl = Panel(parent,h)\n"
"                    elseif h.name == \"SplitterWindow\" then\n"
"                        ctrl = SplitterWindow(parent,h)\n"
"                    elseif h.name == \"Notebook\" then\n"
"                        ctrl = Notebook(parent,h)\n"
"                    elseif h.name == \"Spacer\" then\n"
"                        hbox.AddSpacer(0)\n"
"                    elseif h.name == nil then\n"
"                        for k1,v1 in pairs(h) do hbox[k1] = v1 end\n"
"                    end\n"
"                    if ctrl ~= nil then\n"
"                        if h.layout ~= nil then\n"
"                            for k1,v1 in pairs(h.layout) do ctrl[k1] = v1 end                \n"
"                        end\n"
"                        for k1,v1 in pairs(h) do ctrl[k1] = v1 end                \n"
"                        if ctrl.key ~= nil then _ctrl_table[ctrl.key] = ctrl end\n"
"                        hbox.Add(ctrl)\n"
"                    end\n"
"                else\n"
"                    --TODO: Error Meeesage\n"
"                end\n"
"            end\n"

"        else\n"
"            --TODO: Error Meeesage\n"
"        end  \n"
"        vbox.Add(hbox)\n"
"    end  \n"
"    return vbox\n"
"end\n"

"-------------------------------------------------------------------------------\n"
"-- Window\n"
"-------------------------------------------------------------------------------\n"

"function GetWxCtrl(key)\n"
"	if _ctrl_table[key] ~= nil then\n"
"		return _ctrl_table[key].ctrl\n"
"	else\n"
"		return nil\n"
"	end\n"
"end\n"

"function GetCtrl(key)\n"
"    return _ctrl_table[key]\n"
"end\n"

"function Window(title,icon,layout, width, height) \n"
"    \n"
"    window = {} \n"
"    _ctrl_table = {}\n"
"    window.ctrl = _ctrl_table\n"
"    window.frame = wx.wxFrame (wx.NULL, wx.wxID_ANY, title, wx.wxDefaultPosition, wx.wxSize( width, height ), wx.wxDEFAULT_FRAME_STYLE+wx.wxTAB_TRAVERSAL )\n"
"    \n"
"    window.frame:SetSizeHints( wx.wxDefaultSize, wx.wxDefaultSize )\n"
"    window.Show = function() window.frame:Show() end\n"
"    \n"
"    window.SetMenuBar = function(menu) window.frame:SetMenuBar( MenuBar( window.frame, menu) ) end\n"
"    window.SetToolBar = function(tool) CreateToolBar( window.frame, tool ) end    \n"
"    window.SetStatusBar = function(count) \n"
"        window.StatusBar = window.frame:CreateStatusBar( count, 0, wx.wxID_ANY )\n"
"    end\n"
"    window.SetStatusText = function(text,index) window.StatusBar:SetStatusText(text,index) end\n"

"    window.SetContent = function(content) \n"
"        --window.frame:SetSizer( Layout( window.frame, content ).ctrl )\n"
"        window.frame:SetSizer( BoxPanel( window.frame, content ).ctrl )\n"
"        window.frame:Layout() --TODO: not necessary\n"
"        window.frame:Centre( wx.wxBOTH ) --TODO: not necessary\n"
"    end\n"
"    \n"
"    window.SetTimer = function(handler) \n"
"        window.frame:Connect( wx.wxEVT_TIMER, handler )\n"
"        window.Timer = wx.wxTimer(window.frame, wxID_USER_Index) \n"
"        wxID_USER_Index = wxID_USER_Index + 1\n"
"    end\n"
"    window.StartTimer = function(msec) window.Timer:Start(msec) end\n"
"    window.StopTimer = function() window.Timer:Stop() end  \n"
"    \n"
"    window.GetCtrl = function(name) \n"
"        return _ctrl_table[name];\n"
"    end\n"

"    window.SetIcon = function(name)\n"
"        window.frame:SetIcon(GetIcon(name))\n"
"    end\n"

"	window.Run = function() \n"
"		wx.wxLocale(wx.wxLocale:GetSystemLanguage()) -- TODO\n"
"		wx.wxGetApp():MainLoop()\n"
"	end\n"
"	\n"
"    if icon ~= nil then window.SetIcon(icon) end\n"
"    \n"
"    if layout ~= nil then\n"
"        if layout.menubar   ~= nil then window.SetMenuBar(layout.menubar) end\n"
"        if layout.toolbar   ~= nil then window.SetToolBar(layout.toolbar) end\n"
"        if layout.statusbar ~= nil then window.SetStatusBar(layout.statusbar) end\n"
"        if layout.content   ~= nil then window.SetContent(layout.content) end\n"
"    end\n"
"    return window\n"
"end\n"
;
